import { defineConfig } from 'oxfmt'

export default defineConfig({
  arrowParens: 'avoid',
  bracketSameLine: true,
  bracketSpacing: true,
  embeddedLanguageFormatting: 'auto',
  endOfLine: process.platform === 'win32' ? 'crlf' : 'lf',
  htmlWhitespaceSensitivity: 'strict',
  ignorePatterns: ['.cache/', '.temp/', 'dist/'],
  insertFinalNewline: true,
  jsdoc: {
    addDefaultToDescription: true,
    bracketSpacing: true,
    capitalizeDescriptions: true,
    commentLineStrategy: 'multiline',
    descriptionTag: true,
    descriptionWithDot: false,
    keepUnparsableExampleIndent: true,
    lineWrappingStyle: 'greedy',
    preferCodeFences: true,
    separateReturnsFromParam: false,
    separateTagGroups: true,
  },
  jsxSingleQuote: false,
  objectWrap: 'preserve',
  printWidth: 80,
  proseWrap: 'preserve',
  quoteProps: 'as-needed',
  semi: false,
  singleAttributePerLine: false,
  singleQuote: true,
  sortImports: true,
  sortPackageJson: {
    sortScripts: true,
  },
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
  vueIndentScriptAndStyle: false,
})
